### ISSUE TITLE
Scraper batch cant find OS lenguage or download scraper.exe

### ISSUE THREAD

**Issue by abispac** [paradadf/recaltools#10]
While lauching the bat file i got stuck ,  after deleting the following code , it worked well, have to say i downloaded scraper.exe myself

`:scraperEXE
rem Detect OS architecture
reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /I "x86" >nul && set arch=386 || set arch=amd64

rem Query the API to get the latest tag
set "Uri=https://api.github.com/repos/sselph/scraper/releases/latest"
for /F "delims=" %%a in ('PowerShell Invoke-RestMethod -Method Get -Uri %Uri% ^| find /I "tag_name"') do (
	for /F "tokens=3" %%b in ("%%a") do set scraperVersion=%%b
)

rem Download or update scraper if needed
if exist "scraper.exe" (
	for /F "tokens=* usebackq" %%a in (`scraper.exe -version`) do (
		if "%%a"=="%scraperVersion%" goto systemSelection
		if "%scraperVersion%"=="" echo %dict[4]% & echo. & goto systemSelection
		echo %dict[5]% %%a %dict[6]% %scraperVersion%%dict[7]% & echo.
	)
) else echo %dict[8]% %scraperVersion%%dict[7]% & echo.

rem Build the file name, download url and download the file to the current location
set scraperZip=scraper_windows_%arch%.zip
set scraperURL=https://github.com/sselph/scraper/releases/download/%scraperVersion%/%scraperZip%
PowerShell (New-Object System.Net.WebClient).DownloadFile('%scraperURL%', '%~dp0%scraperZip%')

rem Unzip the scraper and remove unnecessary files
if exist "%scraperZip%" (
	PowerShell Expand-Archive -Path '%scraperZip%' -DestinationPath '.\' -Force
	del LICENSE.txt %scraperZip%	
) else echo %dict[2]% & pause >nul & exit`

**Comment by paradadf** [comment]
Do You have PowerShell installed on your machine? It’s mandatory to be able to download it.

On recalbox forum you said you had a problem with language recognition, but this issue is about something else. What was the error you got about that? There is an option to choose a dictionary. Change **auto** with anything else listed there and try if that solved your other problem.

**Comment by paradadf** [comment]
Closing this as no feedback was  The issue can be reopened if necessary.
