### ISSUE TITLE
Version check fails every time and redownloads scraper

### ISSUE THREAD

**Issue by r0ckarong** [paradadf/recaltools#14]
When one version of scraper is already installed and I run the script I get this error:

```
fastscraper ver. 31.01.2018
./fastscraper: line 180: [: v1.4.5: integer expression expected
Updating sselph scraper from v1.4.5 to v1.4.5, please wait...
```

And then it re-downloads the scraper package. This makes running the script slow because this always takes a couple of seconds even if the current version matches.

I've verified this behavior on macOS and Ubuntu Linux both in zsh and bash.

You're doing an integer comparison between two strings:
https://github.com/paradadf/recaltools/blob/master/fastscraper/fastscraper#L180

The input/output is a string because it has the "v" character and more than one period in it.

I have added #13 to resolve this.

**Comment by paradadf** [comment]
Hi and thanks for your PR!
Actually, I changed the = for the -ge pretty recently because of one user case that wouldn‘t be possible... if you compile a newer version that hasn‘t been released (binaries) yet. One week ago the new version has been uploaded but most of that code has been there for months. I need a greater or equal logic there, but haven‘t really tested that code (batch is ok, shell apparently not) because the person compiling it had an empty string on the version he compiled. Need to check this thoroughly to find out another way to solve it. Or do you have an idea?

**Comment by ironman771** [comment]
To solve the issue please replace the lines 180 and 181:

>if [ "$scraperVersion" -ge "$(./scraper -version)" ]; then :;
>else

with this one:

>if [ "$(./scraper -version)" \< "$scraperVersion" ]; then

and everything will work fine!

[Here](https://www.linuxtechi.com/compare-numbers-strings-files-in-bash-script/) you can find a great guide on comparisons in Bash.

**Comment by paradadf** [comment]
@ironman771 isn´t that the same problem as before? 
`\<` means only **less than** or `/>` **greater than**.

What the script needs is a _working_ **greater or equal** condition as intended here with the _not working_ **-ge**:
`if [ "$scraperVersion" -ge "$(./scraper -version)" ]; then :;`
but your version only give us a **greater than** condition:
`if [ "$scraperVersion" /> "$(./scraper -version)" ]; then :;`

So, for me, it is still missing the equal condition, isn´t it?

**Comment by ironman771** [comment]
In Bash there isn't an operator of "greater or equal" for the STRINGS!! ( -ge works only for numbers)!!
For the strings you have only ** less than** or ** greater than**
The solution is to reverse the terms of inequality! ;)
" IF (my current version) is less than (online version) then download it !
... It's easy...

**Comment by ironman771** [comment]
yes, else statement on line 181 should dissapear. I tested these changes for a long time. I will make a Pull Request...
