### ISSUE TITLE
Rename mame artwork to full name instead of file name?

### ISSUE THREAD

**Issue by mariofenech** [paradadf/recaltools#18]
Hi
Is there a way to scrape mame with full naming rather then the short file name?

I m using this on windows 

Thanks.

**Comment by paradadf** [comment]
If I recall it right, only using mamedb as a source allows that. I don’t think ScreenScraper.fr has that info in its database.

**Comment by mariofenech** [comment]
I mean  that I would like to have the images named in full name instead of as the filename.

**Comment by paradadf** [comment]
Open the bat and see if any of the naming options suits your needs. If not, that is something the scraper itself should manage and not this tool.

**Comment by mariofenech** [comment]
Thanks for your help...I tried many different options but they only change the naming in gamelist which I don t need, not the real scraped image...was trying to use the scraped images in retroarch but it seems it only reads images with full naming rather then filename

**Comment by paradadf** [comment]
I’m closing this issue then for the above reason.
