### ISSUE TITLE
Release Info & language

### ISSUE THREAD

**Issue by cr4nk89** [paradadf/recaltools#9]
Just a small recommondation. Would be nice to have Releases to see the changes. Thank you. Works great so far under macOS V.10.12.2

**Comment by paradadf** [comment]
It is in my opinion difficult to have proper releases with the kind of code this project has. The changes are usually minimal (but sometimes with great impact) and usually very frequent.
You can see the changes if you look at the commits, I try to document it as good as I can.
https://github.com/paradadf/recaltools/commits/master

The real interesting changes and what I try to follow is here (regarding fastscraper):
https://github.com/sselph/scraper/releases

**Comment by cr4nk89** [comment]
Ok that makes sense. Another small idea: What about different languages?  I mean since the tool doesnt use much words its not realy necessary. Though it can be done more easy. 
You can get the language with
`locale | awk -F '"' '/LANG=/ {print $2;}'`
Compare them with the languages we have and then get a number and 'awk print $number' the correct language out of a small dictionary. I think its not a big feature, but nice to have.

**Comment by paradadf** [comment]
Why not? :)
Does this works on a mac?
`locale | grep LANG= | cut -d= -f2 | cut -d_ -f1`

**Comment by cr4nk89** [comment]
Seems not to work as espected
`"de`

I changed it to:
`locale | grep LANG= | cut -d'"' -f2 | cut -d_ -f1`

==> `de`

**Comment by paradadf** [comment]
It appears that the output of `locale` is different on mac and linux. In linux the line looks like this:
`LANG=en_US.UTF-8`
Could you show me how the line looks on you mac, please?

**Comment by cr4nk89** [comment]
`LANG="de_DE.UTF-8"`
If I use a second cut it works for mac. Can you test if it works for you as well without error ?
`locale | grep LANG= | cut -d'=' -f2 | cut -d '"' -f2 | cut -d_ -f1`
should just skip this `cut` because there no `"`

**Comment by paradadf** [comment]
Perfect, that works on linux too.
I'll work on adding this feature soon, thanks!

**Comment by cr4nk89** [comment]
You're welcome! Maybe I can support you somehow with ideas or code... Just tried some easy stuff, but stuck at the moment. Maybe beacause it's late now. 

 Dictionary; some words to test
```
en=('start'     'stop '     'continue')
de=('start'     'stopp'     'fortfahren')
fr=('commencer' 'arrêt'     'continuer')
```
e.g. echo stop in english. If the Dictionary is used like this, even sentences could be easy stored and translated. Just the index needs to be the same. 

`echo  ${en[1]}`

Just need to get the system language now. (As we already figured out before)
Get language and store to getLang

`getLang=$(locale | grep LANG= | cut -d'=' -f2 | cut -d '"' -f2 | cut -d_ -f1)`

Here I stuck. Can't get ${getLang[1]} to print out stop in system language :(

**Comment by paradadf** [comment]
I'm not sure how to echo the variable array name without setting a variable before. But for illustration, something like this would work. 

```
en=('start'	'stop'	'continue')
de=('start'	'stopp'	'fortfahren')
fr=('commencer'	'arrêt'	'continuer')

osLang=$(locale | grep LANG= | cut -d'=' -f2 | cut -d '"' -f2 | cut -d_ -f1)
echo OS languague: $osLang

l_dictionary=$osLang[@]
echo $osLang dictionary: ${!l_dictionary}

l_start=$osLang[0]
echo start in $osLang: ${!l_start}

l_stop=$osLang[1]
echo stop in $osLang: ${!l_stop}

l_continue=$osLang[2]
echo continue in $osLang: ${!l_continue}
```

**Comment by cr4nk89** [comment]
💯 points. Started with coding right before you uploaded the multilang version. At least I can provide a Excel file to create a dictionary.

**Comment by paradadf** [comment]
Sorry about that! I did it because I thought you were waiting for it and I like contributors.
The excel table is a very good idea, I don't know how many people are willing to translate it though 😅.
I changed some words to make it easier and understandable in any  language.
Also, I didn't separated the strings so much as you. E.g. "ERROR:"... from the rest. The code is  more understandable with less such variables.

About your comment about "cd" on macOS, don'T you get a  message saying it isn't implemented yet? I haven't found a native folder browser like zenity on linux for macOS. Ubuntu comes with it already installed. Do you know if there is such binaries natively installed? I read you can install zenity over homebrew, but I can't test it. Although I would still prefer not needing to install anything.

About the languages... You can actually run fastscraper directly from your Pi, thus the check on recalbox's languague. That option isn't properly documented yet XD

**Comment by cr4nk89** [comment]
On macOS is nothing like zenity. I was looking for something like this some time ago. I ran the script in debug and the interesting is:

```bash
+ echo 'Opening Folder Browser...'
Opening Folder Browser...
+ case "$OSTYPE" in
+ echo 'Folder Browser for macOS not implemented yet, sorry!'
Folder Browser for macOS not implemented yet, sorry!
+ cd /Users/KevinWestphal/Downloads/JD/scraper
+ clear
```

`clear` shouldn't be there. Thats why I don't see the message.

```bash
# Check if scraping from network drive and show warning about stopping ES
cd "$romsDir" && clear && echo "${dict[12]} $romsDir"
if [[ $(df "$romsDir" | grep '^//') == "//"* ]]; then echo "${dict[13]}"; fi
echo ""
```
If you want I can put `es` and `en`in the Excel and add `de`.

**Comment by paradadf** [comment]
This is what I found about zenity on macOS
http://brewformulas.org/Zenity

I just updated fastscraper[.bat] adding a few new strings. There are differences between the bash and the batch concerning the format of the array.

(And I deleted the `clear`, thanks for pointing that out!)

**Comment by paradadf** [comment]
@cr4nk89 I'm closing this as the multilanguage suppport has been already fully added and I see no point of having releases for a  code that doesn't need compilation.
